---
name: Publish Binaries

on:
  push:
    tags: v*

jobs:
  build:
    runs-on: ${{ matrix.build-type.os }}

    strategy:
      max-parallel: 2
      matrix:
        build-type: [
          {os: "windows-2019", arch: "x86"},
          {os: "windows-2019", arch: "x64"},
          {os: "macos-latest", arch: "x64"},
          {os: "ubuntu-latest", arch: "x64"},
        ]
        node-version: [14.x, 16.x, 18.x, 22.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.1
        if: ${{ matrix.build-type.os == 'windows-latest' }}
        with:
          vs-version: '[17.0,18.0)'

      - name: Install dependencies
        run: npm ci

      - name: Build TypeScript project
        run: npm run build-es

      - name: Build binary
        run: npm run build-binary-${{ matrix.build-type.arch }}

      - name: Push binaries
        env:
          NODE_PRE_GYP_GITHUB_TOKEN: ${{ secrets.NODE_PRE_GYP_GITHUB_TOKEN }}
        run: npm run push-binary
