---
name: Publish Binaries

on:
  push:
    tags: v*
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.build-type.os }}

    strategy:
      max-parallel: 4
      matrix:
        build-type: [
          {os: "ubuntu-latest", arch: "x64"},
          {os: "windows-2021", arch: "x64"},
          {os: "windows-2021", arch: "x86"},
        ]
        node-version: [18.x, 22.x]

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: 'https://registry.npmjs.org'
          # cache: 'yarn'

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.1
        if: ${{ matrix.build-type.os == 'windows-latest' }}
        with:
          vs-version: '[17.0,18.0)'

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Fix CRLF line endings on Linux/macOS
        if: startsWith(matrix.build-type.os, 'ubuntu') || startsWith(matrix.build-type.os, 'macos')
        run: |
          sudo apt-get install -y dos2unix
          find node_modules/.bin -type f -exec dos2unix {} +
      
      - name: Build TypeScript project
        run: yarn build-es

      - name: Build binary
        run: yarn build-binary-${{ matrix.build-type.arch }}

      - name: Push binaries
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          NODE_PRE_GYP_GITHUB_TOKEN: ${{ secrets.NODE_PRE_GYP_GITHUB_TOKEN }}
        run: yarn publish:all
