---
name: Publish Binaries

on:
  push:
    tags: v*
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.build-type.os }}

    strategy:
      max-parallel: 2
      matrix:
        build-type: [
          {os: "windows-2019", arch: "x86"},
          {os: "windows-2019", arch: "x64"},
          {os: "ubuntu-latest", arch: "x64"},
        ]
        node-version: [18.x, 22.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          # cache: 'yarn'

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.1
        if: ${{ matrix.build-type.os == 'windows-latest' }}
        with:
          vs-version: '[17.0,18.0)'

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Build TypeScript project
        run: yarn build-es

      - name: Build binary
        run: yarn build-binary-${{ matrix.build-type.arch }}

      - name: Set up npm auth
        run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > ~/.npmrc

      - name: Push binaries
        env:
          NODE_PRE_GYP_GITHUB_TOKEN: ${{ secrets.NODE_PRE_GYP_GITHUB_TOKEN }}
        run: yarn push-binary
